# Imagem Base
FROM python:3.9

# Pasta de trabalho
WORKDIR /app

# Copiando script
COPY sensor_producer.py .
# COPY entrypoint.sh .

# Instalando dependências
RUN pip install kafka-python faker

# Rodando script
# ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["python", "sensor_producer.py"]