# Imagem Base
FROM python:3.9

# Pasta de trabalho
WORKDIR /app

# Copiando script
COPY . .

# Instalando dependências
RUN pip install kafka-python==2.2.11 faker==37.4.0

# Rodando script
CMD ["python", "run.py"]