# Imagem Base
FROM python:3.9

# Pasta de trabalho
WORKDIR /app

# Copiando script
COPY sensor_consumer.py .

# Instalando dependências
RUN pip install kafka-python simplejson

# Rodando script
CMD ["python", "sensor_consumer.py"]